site_name: Awesome Platform Engineering Tools
site_description: A curated list of platform solutions, tools, practices and resources for Platform Engineering.
site_author: Saif(eddine) RAJHI
repo_name: seifrajhi/awesome-platform-engineering-tools
repo_url: https://github.com/seifrajhi/awesome-platform-engineering-tools
docs_dir: "docs"
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - tabs
    - content.code.copy
    - announce.dismiss
    - header.autohide
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seifrajhi
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/rajhisaifeddine
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rajhi-saif/
nav:
  - "Awesome Platform Engineering Tools": "index.md"
