name: deploy to mkdocs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-static-i18n==1.2.0
      - run: ls
      - run: cp README.md content/index.md
      - run: mkdocs gh-deploy --force
